name: CI
env:
  ELIXIR_VERSION: "1.15.4"
  MIX_ENV: test
  OTP_VERSION: "25.2.1"
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres

on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: market_maker_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      timescaledb:
        image: timescale/timescaledb:latest-pg14
        ports: ["5434:5432"]
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: market_maker_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-v1-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-v1-
      - uses: actions/cache@v3
        with:
          path: _build/test
          key: ${{ runner.os }}-test-build-v1
          restore-keys: |
            ${{ runner.os }}-test-build-v1
      - name: Install Dependencies
        run: mix do deps.get, deps.compile
      - name: Compile app
        run: mix compile --force --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      - name: Credo
        run: mix credo --strict
      - name: Run Tests
        run: mix test
        env:
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}